# Generated by Django 5.1.4 on 2025-05-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozmecapp', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
