# Generated by Django 5.1.4 on 2025-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozmecapp', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
