# Generated by Django 5.1.4 on 2025-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozmecapp', '0007_offerenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='seats_available',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='upcoming_batch',
            field=models.DateField(blank=True, null=True),
        ),
    ]
