# Generated by Django 5.1.4 on 2025-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozmecapp', '0013_remove_eventregistration_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
